### ISSUE TITLE
Getting "422: Unprocessable Content" when creating a product

### ISSUE THREAD

**Issue by t-88** [Chargily/chargily-pay-javascript#5]
# Environment Details: 
   os info: linux (mint os), 
   node version: v20.10.0 
   latest version chargily

# Steps to Reproduce:
```js
import { ChargilyClient } from '@chargily/chargily-pay';

const client = new ChargilyClient({
  api_key: 'test_sk_xxxx',
  mode: 'test', 
});

async function main()  {
    const newProduct = await client.createProduct({
        name: 'Awesome Product',
        description: 'A description of your awesome product',
        images: ['https://example.com/image.png'],
        metadata: {
          category: 'Electronics',
        },
    });
}   
main();
```
# Error Messages:
```
/home/XXXX/Desktop/XXXX/XXXXXXXXX/node_modules/@chargily/chargily-pay/lib/classes/client.js:93
                        throw new Error("Failed to make API request: ".concat(error_1));
                              ^

Error: Failed to make API request: Error: API request failed with status 422: Unprocessable Content
    at ChargilyClient.<anonymous> (/home/XXXX/Desktop/XXXX/XXXXXXXXX//node_modules/@chargily/chargily-pay/lib/classes/client.js:93:31)
    at step (/home/XXXX/Desktop/XXXX/XXXXXXXXX//node_modules/@chargily/chargily-pay/lib/classes/client.js:33:23)
    at Object.next (/home/XXXX/Desktop/XXXX/XXXXXXXXX//node_modules/@chargily/chargily-pay/lib/classes/client.js:14:53)
    at fulfilled (/home/XXXX/Desktop/XXXX/XXXXXXXXX//node_modules/@chargily/chargily-pay/lib/classes/client.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

# Expected
i expect it to create a new product and i see it in the chargily frontend

**Comment by ruzolut** [comment]
Hello, thank you for reporting this issue.

I've reproduced your issue, and I had the same error, after some debugging it appears that the request fails because of the images param, when I removed it the request passed successfully and the product was created and I received a response back.

<img width="636" alt="Screenshot 2024-03-19 at 1 24 06 PM" src="https://github.com/Chargily/chargily-pay-javascript/assets/37586909/32393cf6-7d6e-417e-8063-639322ca4f84">
<img width="609" alt="Screenshot 2024-03-19 at 1 25 52 PM" src="https://github.com/Chargily/chargily-pay-javascript/assets/37586909/b81e0c75-85e2-41fb-8304-569e3fd0df06">

I'm not exactly sure why this happened, but I'll certainly dig deeper to find what causes it. For the meantime, you could comment/remove the images param until I investigate further.

I will also report this to the development team at Chargily because I received an error when I tried this in their "Create product" [API Reference page](https://dev.chargily.com/pay-v2/api-reference/products/create), which implies that the problem could possibly be in their API and not client-side.

Thank you again for reporting the issue,
I will be adding unit tests soon, to discover more bugs.

Please don't hesitate on reporting any other bugs that come your way.

Best regards.

Mentions:
@ChargilyDev

**Comment by ruzolut** [comment]
@t-88 did you get it to work the way I did?

Please provide feedback so we could work on this issue.

Thank you!

**Comment by t-88** [comment]
yep after commenting images in the **createProduct** function the request works and the product gets created.
i just wanted to test the api, i switched to using python api for now for testing

**Comment by ruzolut** [comment]
@ChargilyDev I'm re-opening this issue until we get the problem fixed, thank you @t-88 for reporting it!

**Comment by theHocineSaad** [comment]
It's working fine.

The error you're encountering is due to passing an incorrect image URL, such as the one you used: `https://example.com/image.png`.

When you provide an invalid, unsupported, or larger-than-2MB image URL, you'll receive the following response from Chargily Pay's API:

```
{
  "message": "Unsupported image type: https://example.com/image.png, we only accept JPG, JPEG, PNG, WEBP, SVG and GIF that are less than 2MB images.",
  "errors": {
    "images.0": [
      "Unsupported image type: https://example.com/image.png, we only accept JPG, JPEG, PNG, WEBP, SVG and GIF that are less than 2MB images."
    ]
  }
}
```

It's preferable for the package to display this message instead of throwing an exception.
