### ISSUE TITLE
Unused invoice_id attribute in checkout object

### ISSUE THREAD

**Issue by AyoubKaz07** [Chargily/chargily-pay-javascript#6]
The checkout object has an `invoice_id` attribute
https://github.com/Chargily/chargily-pay-javascript/blob/main/src/types/data.ts#L204
But as we see in `CreateCheckoutParams`
https://github.com/Chargily/chargily-pay-javascript/blob/main/src/types/param.ts#L92
the attribute is not used and there's no way to set it, so the checkout object will always contain a null `invoice_id`
The trivial workaround is using a custom `invoice_id` in `metadata`
Like: `metadata: {
                        invoice_id: invoice_id
                    }
`

**Comment by rofazayn** [comment]
I believe an invoice is only generated once the checkout is paid, why do you want to set an invoice id for a checkout?

**Comment by rofazayn** [comment]
I personally believe an invoice is only generated once the checkout is initiated, the [documentation](https://dev.chargily.com/pay-v2/api-reference/checkouts/create) does not show that you can specify a certain invoice id upon checkout creation, that's why I haven't added it to the params of the checkout creation method.

There are two possible reasons why this work like that:
- Chargily is the one responsible for generating the invoice and returns the invoice_id once a checkout is paid.
- Chargily haven't implemented invoice creation/handling features just yet.

**Comment by ruzolut** [comment]
I personally believe an invoice is only generated once the checkout is initiated, the [documentation](https://dev.chargily.com/pay-v2/api-reference/checkouts/create) does not show that you can specify a certain invoice id upon checkout creation, that's why I haven't added it to the params of the checkout creation method.

There are two possible reasons why this works like that:
- Chargily is the one responsible for generating the invoice and returns the invoice_id once a checkout is initiated.
- Chargily haven't implemented invoice creation/handling features just yet.

**Comment by AyoubKaz07** [comment]
> * Chargily haven't implemented invoice creation/handling features just yet.
Reasonable enough.
Thank you

**Comment by ruzolut** [comment]
@AyoubKaz07 you are most welcome, let me know if you have any other inquiries.
